[package]
name = "blueroute-daemon"
description = "BlueRoute background networking daemon."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blueroute-core = { path = "../../crates/blueroute-core" }
blueroute-linux = { path = "../../crates/blueroute-linux" }
blueroute-protocol = { path = "../../crates/blueroute-protocol" }
futures-lite = "2.6.0"
zbus = { version = "5.19.0", default-features = false, features = ["async-io"] }

[dev-dependencies]
async-io = "2.6.0"

[lints]
workspace = true
