[package]
name = "blueroute-linux"
description = "Linux system adapters for BlueRoute."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
blueroute-core = { path = "../blueroute-core" }
async-io = "2.6.0"
futures-lite = "2.6.0"
rustix = { version = "1.1.4", features = ["net"] }
zbus = { version = "5.19.0", default-features = false, features = ["async-io"] }

[lints]
workspace = true
